### ISSUE TITLE
Lab code of conduct

### ISSUE THREAD

**Issue by Aariq** [BrunaLab/REU-resources#2]
Develop a lab code of conduct.  This might be a separate repository, or a page on the Bruna Lab website, that can be linked to. 

Examples:
- https://github.com/BahlaiLab/Policies

**Comment by Aariq** [comment]
Ethan White has one too: https://www.weecology.org/lab-wiki/code-of-conduct/

**Comment by embruna** [comment]
Added a [repo](https://github.com/BrunaLab/Code_of_Conduct). still needs one last bit of info, but a good start
